- composer.json
- tests/EventTest.php
- Updated composer.json file
- Update PHP version to 5.5.9
- Added prefer stable
> Update php version

- README.md
> Fix PHP syntax error

- CHANGELOG.md
- composer.json
- src/Console/Command/ScheduleRunCommand.php
- src/EventRunner.php
> Fix high cpu usage

- CHANGELOG.md
- appveyor.yml
- composer.json
- phpunit.xml
- src/Event.php
- tests/EventTest.php
This PR fixes https://github.com/lavary/crunz/issues/39.
> Fix Event::in on windows

- CHANGELOG.md
- src/Event.php
- tests/EventTest.php
Fixes https://github.com/lavary/crunz/issues/83
> Make comparing date segments strict.

- CHANGELOG.md
- Vagrantfile
- appveyor.yml
- composer.json
- config/services.xml
- src/Application.php
- src/Event.php
- src/EventRunner.php
- src/HttpClient/CurlHttpClient.php
- src/HttpClient/HttpClientException.php
- src/HttpClient/HttpClientInterface.php
- src/HttpClient/HttpClientLoggerDecorator.php
- src/Logger/ConsoleLogger.php
- src/Logger/ConsoleLoggerInterface.php
- src/Pinger/PingableException.php
- src/Pinger/PingableInterface.php
- src/Pinger/PingableTrait.php
- src/Schedule.php
- tests/Unit/EventRunnerTest.php
- tests/Unit/Logger/ConsoleLoggerTest.php
- tests/Unit/Pingable.php
- tests/Unit/Pinger/PingableTest.php
- vendor-bin/cs-fixer/composer.lock
This PR removes `Guzzle` dependency as there is no need for fully featured http client.
> Remove guzzle

- CHANGELOG.md
- README.md
- crunz
PRs: https://github.com/lavary/crunz/pull/136, https://github.com/lavary/crunz/pull/137.
> Release 1.10.

- CHANGELOG.md
- README.md
- crunz
PRs:
1. https://github.com/lavary/crunz/pull/139
> Release v1.10.1

- README.md
There is no need to rush v2, extra time will help to stabilize API and resolve bugs.
> Change roadmap.

- README.md
To reduce confusion when creating PR specify preferred, `1.x`, branch in README.
> Add info about target 1.x branch.

- CHANGELOG.md
- src/Console/Command/ScheduleRunCommand.php
- tests/Unit/EventTest.php
- vendor-bin/cs-fixer/composer.lock
Do not allow other types than string to be passed as a string number, this PR fixes https://github.com/lavary/crunz/issues/156.
> Accept only string task number.

- CHANGELOG.md
- src/Event.php
- src/EventRunner.php
- tests/Unit/EventTest.php
This PR fixes https://github.com/lavary/crunz/issues/161.
> Fix command error output

- CHANGELOG.md
- README.md
- crunz
- Crunz doesn't provide error log when emailing, issue [#161](https://github.com/lavary/crunz/issues/161) - PR [#162](https://github.com/lavary/crunz/pull/162)
> Release v1.11.0-beta.2

- Vagrantfile
- config/services.php
- src/Task/Collection.php
Also install `hirak/prestissimo` in dev VM.
> Improve task collection debugging

- .gitattributes
- .travis.yml
- CHANGELOG.md
- changelog-linker.yml
- composer.json
- vendor-bin/changelog-linker/composer.json
- vendor-bin/changelog-linker/composer.lock
Make all entries looks familiar with help of https://github.com/symplify/changeloglinker.
> Improve CHANGELOG.md

- docker-compose.yml
- docker/php71/Dockerfile
- docker/php71/php.ini
- src/Configuration/Definition.php
- src/Event.php
| Fixed tickets | https://github.com/lavary/crunz/issues/172  
Both Symfony deprecations fixed.
> Remove symfony 4 2 deprecations

- README.md
- composer.json
> Change dev branches

- phpunit.xml
This PR improves PHPUnit's test suites configuration, configuration should be forward compatible with PHPUnit 7+.
> Fix PHPUnit's test suites name

- .gitattributes
- .gitignore
- box.json
- vendor-bin/box/composer.json
- vendor-bin/box/composer.lock
- vendor-bin/changelog-linker/composer.lock
> Add `humbug/box` to dev tools

- src/Event.php
- src/Process/Process.php
- tests/TestCase/EndToEnd/Environment/Environment.php
This PR adds `\Crunz\Process\Process` which is abstract layer between Crunz and `symfony/process` package.
> Introduce Crunz\Process\Process

- crunz
- src/Event.php
- tests/EndToEnd/ClosureRunTest.php
- tests/Unit/EventTest.php
- tests/resources/tasks/ClosureTasks.php
| Fixed tickets | https://github.com/lavary/crunz/issues/135
This PR fixes regression caused by `v1.11` release.
> Fix Crunz bin path when running closures

- crunz
This PR fixes `_DIR_` constant introduced in #209.
> Fix _DIR_ const name

- config/services.php
- src/Configuration/Definition.php
- src/Logger/LoggerFactory.php
- src/Task/Timezone.php
- tests/Unit/Logger/LoggerFactoryTest.php
- vendor-bin/box/composer.lock
- vendor-bin/changelog-linker/composer.lock
- vendor-bin/cs-fixer/composer.lock
- vendor-bin/phpstan/composer.lock
- vendor-bin/phpunit/composer.lock
This PR changes fallback timezone for `timezone_log` option from `UTC` to system's default to avoid possible BC break.
> Fallback to system's timezone instead of 'UTC'

- composer.json
- phpstan.neon
- src/Event.php
- tests/Unit/EventTest.php
> Make "\Crunz\Event::setProcess" private

- CHANGELOG.md
- README.md
- crunz
> Release v2.0.0

- CHANGELOG.md
- README.md
- crunz
> Release v1.12.1

- CHANGELOG.md
- README.md
- crunz
> Release v2.0.1

- .travis.yml
- bootstrap.php
- phpstan.neon
- src/Event.php
- tests/Unit/Console/Command/ScheduleRunCommandTest.php
- tests/resources/patches/php-mock-object-71.php
- tests/resources/patches/php-mock-object-org.php
> Fix PHP 7.4 compatibility

- vendor-bin/phpunit/composer.lock
> Update PHPUnit to avoid PHP7.4 deprecations on 2.x branch

- CHANGELOG.md
- README.md
- crunz
> Release v1.12.2

- CHANGELOG.md
- README.md
- crunz
- [#244] Fix AppVeyor CI
- [#243] Sandbox task loading
- [#245] Fix PHP 7.4 compatibility
- [#251] Update PHPUnit to avoid PHP7.4 deprecations on 2.x branch
> Release v2.0.2

- src/Event.php
- src/EventRunner.php
- tests/Unit/EventRunnerTest.php
| Fixed tickets | #260 
Locks should be released on error.
> Release lock on error

- CHANGELOG.md
- README.md
- crunz
> Release v1.12.3

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#268] Fix Symfony 4.4 deprecations
> Release v1.12.4

- .gitattributes
- .php_cs.dist
- .travis.yml
- composer-install.php
- composer.json
> Test against all supported Symfony versions

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#268] Fix Symfony 4.4 deprecations
- [#270] Update symfony/phpunit-bridge
- [#271] Move PHPUnit to main composer.json
- [#272] Test against all supported Symfony versions
> Release v2.0.4

- .travis.yml
- composer.json
- phpstan.neon
- src/Event.php
- tests/Unit/EventRunnerTest.php
- tests/Unit/EventTest.php
| Fixed tickets | https://github.com/lavary/crunz/issues/265
> Add Symfony 5 support

- .php_cs.dist
- phpstan.neon
- src/Application.php
- src/Configuration/Configuration.php
- src/Console/Command/TaskGeneratorCommand.php
- src/Event.php
- src/EventRunner.php
- src/Logger/Logger.php
- src/Schedule.php
- src/Schedule/ScheduleFactory.php
- src/Task/Collection.php
- vendor-bin/box/composer.lock
- vendor-bin/cs-fixer/composer.lock
- vendor-bin/phpstan/composer.lock
> Update dev tools

- config/services.php
- src/Application.php
- src/UserInterface/Cli/ClosureRunCommand.php
- tests/Unit/UserInterface/Cli/ClosureRunCommandTest.php
`closure:run` was never intended to be part of public API so hide it.
> Hide closure:run command

- CHANGELOG.md
- README.md
- composer.json
- crunz
> Release v2.1.0

- README.md
- config/services.php
- phpstan.neon
- src/Application.php
- src/Application/Cron/CronExpressionFactoryInterface.php
- src/Application/Cron/CronExpressionInterface.php
- src/Application/Query/TaskInformation/TaskInformation.php
- src/Application/Query/TaskInformation/TaskInformationHandler.php
- src/Application/Query/TaskInformation/TaskInformationView.php
- src/Infrastructure/Dragonmantank/CronExpression/DragonmantankCronExpression.php
- src/Infrastructure/Dragonmantank/CronExpression/DragonmantankCronExpressionFactory.php
- src/Schedule/ScheduleFactory.php
- src/UserInterface/Cli/DebugTaskCommand.php
- tests/EndToEnd/DebugTaskTest.php
- tests/Unit/Application/Cron/AbstractCronExpressionTest.php
- tests/Unit/Application/Query/TaskInformation/TaskInformationHandlerTest.php
- tests/Unit/Infrastructure/Dragonmantank/CronExpression/DragonmantankCronExpressionTest.php
- tests/Unit/Schedule/ScheduleFactoryTest.php
| Fixed tickets | https://github.com/lavary/crunz/issues/56
This PR add `task:debug` command to check task next execution times and other information.
> Add task:debug command

- .travis.yml
This PR fixes parsing TravisCI configuration, reported by Travis' dashboard.
> Improve TravisCI configuration

- README.md
> Add "v3.x" to roadmap

- appveyor.yml
- config/services.php
- src/Application/Query/TaskInformation/TaskInformationHandler.php
- src/Application/Service/ConfigurationInterface.php
- src/Configuration/Configuration.php
- src/Console/Command/ScheduleListCommand.php
- src/Console/Command/ScheduleRunCommand.php
- src/Console/Command/TaskGeneratorCommand.php
- src/EventRunner.php
- src/Logger/Logger.php
- src/Logger/LoggerFactory.php
- src/Mailer.php
- src/Task/Collection.php
- src/Task/Timezone.php
- tests/TestCase/FakeConfiguration.php
- tests/Unit/Application/Query/TaskInformation/TaskInformationHandlerTest.php
- tests/Unit/Console/Command/ScheduleRunCommandTest.php
- tests/Unit/EventRunnerTest.php
- tests/Unit/Logger/LoggerFactoryTest.php
- tests/Unit/MailerTest.php
- tests/Unit/Task/TimezoneTest.php
> Add ConfigurationInterface

- composer.json
- config/services.php
- src/Application/Service/ClosureSerializerInterface.php
- src/Event.php
- src/Infrastructure/Opis/Closure/OpisClosureSerializer.php
- src/UserInterface/Cli/ClosureRunCommand.php
- tests/TestCase/UnitTestCase.php
- tests/Unit/EventTest.php
- tests/Unit/UserInterface/Cli/ClosureRunCommandTest.php
`jeremeamia/superclosure` package is no longer maintained so use proposed `opis/closure`.
> Migrate to "opis\closure"

- README.md
- composer.json
- config/services.php
- src/Application/Service/LoggerFactoryInterface.php
- src/Configuration/Definition.php
- src/EventRunner.php
- src/Infrastructure/Psr/Logger/PsrStreamLogger.php
- src/Infrastructure/Psr/Logger/PsrStreamLoggerFactory.php
- src/Logger/Logger.php
- src/Logger/LoggerFactory.php
- tests/EndToEnd/ConfigProviderTest.php
- tests/EndToEnd/LoggerTest.php
- tests/TestCase/EndToEnd/Environment/Environment.php
- tests/TestCase/FakeConfiguration.php
- tests/TestCase/Faker.php
- tests/TestCase/TemporaryFile.php
- tests/Unit/Infrastructure/Psr/Logger/PsrStreamLoggerTest.php
- tests/Unit/Logger/LoggerFactoryTest.php
- tests/resources/tasks/FailTasks.php
| Fixed tickets | https://github.com/lavary/crunz/issues/259
> Implement logger factory rfc

- README.md
> Add "status" column to roadmap

- .travis.yml
> Test Symfony 5.1 compatibility

- README.md
| Fixed tickets | https://github.com/lavary/crunz/issues/317
> Remove "Event::monthlyOn" from documentation because method is not implemented

- .travis.yml
- appveyor.yml
- composer-install.php
- docker/php72/Dockerfile
- tests/TestCase/EndToEnd/Environment/Environment.php
> Use composer v2

- .travis.yml
- composer.json
> Drop Symfony 5.0 support

- src/Application/Service/ClosureSerializerInterface.php
- src/Event.php
- src/Infrastructure/Opis/Closure/OpisClosureSerializer.php
- tests/EndToEnd/ClosureRunTest.php
- tests/TestCase/EndToEnd/Environment/Environment.php
- tests/Unit/Service/AbstractClosureSerializerTest.php
- tests/Unit/Service/OpisClosureSerializerTest.php
- tests/resources/tasks/NoOverlappingClosureTasks.php
> Fix lock key on closures

- .travis.yml
- README.md
- composer-install.php
- composer.json
- docker/php80/Dockerfile
- tests/TestCase/EndToEnd/Environment/Environment.php
- tests/Unit/UserInterface/Cli/ClosureRunCommandTest.php
- tests/resources/tasks/ClosureTasks.php
> Full PHP v8 support

- .github/workflows/code_checks.yaml
> Fix missing "composer version" command in CI

- .github/workflows/code_checks.yaml
> Fix dependencies versions in "static_analysis" job

- .github/workflows/code_checks.yaml
> Do not test PHP v8.1

- .github/workflows/code_checks.yaml
> Fix workflows syntax

- src/Infrastructure/Psr/Logger/EnabledLoggerDecorator.php
- src/Infrastructure/Psr/Logger/PsrStreamLoggerFactory.php
- tests/TestCase/Logger/SpyPsrLogger.php
- tests/Unit/Infrastructure/Psr/Logger/EnabledLoggerDecoratorTest.php
- tests/Unit/Infrastructure/Psr/Logger/PsrStreamLoggerFactoryTest.php
| Fixed tickets | https://github.com/lavary/crunz/issues/318
> Fix disabling logger not working

- CHANGELOG.md
- README.md
- crunz
- [#329] Full PHP v8 support
- [#334] Fix disabling logger not working
- [#339] Add GitHub actions
- [#340] Fix workflows syntax
- [#341] Update dev tools
> Release v2.2.3

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#333] Include symlinks in Finder
> Release v2.2.4

- .github/workflows/code_checks.yaml
- composer.json
> Drop Symfony v3.4 support

- .github/workflows/code_checks.yaml
- composer.json
> Drop Symfony v5.1 support

- phpstan.neon
- src/Configuration/Definition.php
- src/Event.php
- src/Process/Process.php
- tests/Unit/EventTest.php
> Remove Symfony BC layer

- composer.json
PR relates to https://github.com/lavary/crunz/pull/330
Updating `ragonmantank/cron-expression` dependency can change how often some task will run, more here: https://github.com/dragonmantank/cron-expression/blob/master/CHANGELOG.md#300---2020-03-25
> Require package "dragonmantank/cron-expression" at least "v3.1"

- CHANGELOG.md
- README.md
- crunz
> Release v3.0.0

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#361] Log to specific event log file
> Release v2.3.1

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#361] Log to specific event log file
> Release v3.0.1

- composer.json
- src/Mailer.php
> Replace Swiftmailer with Symfony mailer

- CHANGELOG.md
- README.md
- composer.json
PR:
- [#385] Replace Swiftmailer with Symfony mailer
> Release v3.1.0

- .github/workflows/code_checks.yaml
- composer-install.php
- composer.json
- tests/TestCase/EndToEnd/Environment/Environment.php
- tests/Unit/HttpClient/StreamHttpClientTest.php
> Test PHP 8.1 in CI

- .github/workflows/code_checks.yaml
- composer-install.php
> Rework ci jobs

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#390] Symfony 6 Support
- [#393] Drop Symfony 5.2 support
- [#394] Drop Symfony 5.3 support
- [#396] Remove "opis/closure" and use "laravel/serializable-closure" instead
- [#397] Test PHP 8.1 in CI
- [#395] Rework CI jobs
- [#398] Add hourlyAt()
> Release v3 2 0

- crunz
| Fixed tickets | https://github.com/lavary/crunz/issues/400
> Fix version number
