- .gitignore
- CHANGELOG.md
- composer.json
- config/services.xml
- crunz
- src/Console/Command/ScheduleRunCommand.php
- src/Console/CommandKernel.php
This will allow to create better unit tests and should ease maintaining.
> Introduce DI container

- CHANGELOG.md
- src/EventRunner.php
Fixes https://github.com/lavary/crunz/issues/64
> Send output by email only if it is not empty.

- CHANGELOG.md
- README.md
- Vagrantfile
- composer.json
- config/services.xml
- crunz.yml
- src/Application.php
- src/Configuration/Definition.php
- src/Console/Command/Command.php
- src/Console/Command/ConfigGeneratorCommand.php
- src/Console/Command/ScheduleRunCommand.php
- src/Event.php
- src/EventRunner.php
- src/Output/VerbosityAwareOutput.php
- src/Schedule.php
- src/Task/Timezone.php
- src/Timezone/Provider.php
- src/Timezone/ProviderInterface.php
- tests/Functional/ConfigProviderTest.php
- tests/Unit/EventTest.php
- tests/Unit/Timezone/ProviderTest.php
- tests/crunz.yml
* Added timezone option.
* Do not require symfony/debug it is not in use.
* Report all error in CLI.
* Fix type hints.
* Type hint improved.
* Added configuration to tests env.
* Added null values.
* Added timezone provider.
* Added tasks timezone.
* Require symfony/filesystem.
* Add composer as a non-privileged user.
* Added VerbosityAwareOutput.
* Added TODO.
* Improved type hint.
* Added deprecation handler.
* Make calculation task's run date aware of timezone.
* Ask about timezone while generating config file.
* Updated changelog.
> Added timezone option (#94)

- CHANGELOG.md
- composer.json
- config/services.xml
- src/HttpClient/FallbackHttpClient.php
- src/HttpClient/StreamHttpClient.php
- tests/Unit/HttpClient/StreamHttpClientTest.php
`ext-curl` is no longer required so users without this extension can install newest version of Crunz, also there is fallback to `StreamHttpClient` (requires `allow_url_fopen` turned on) in case user want to `ping` but do not have `ext-curl` installed/enabled.
> Do not require cURL extension

- composer.json
- config/services.php
- src/Configuration/Configuration.php
- tests/Unit/Configuration/ConfigurationTest.php
There is no need to install this dependency as it was used only in one place, in easy to replace with native code context.
> Remove symfony\property-access dependency

- composer.json
- config/services.php
- src/Application.php
- src/Configuration/Configuration.php
- src/Console/Command/ConfigGeneratorCommand.php
- src/Console/Command/ScheduleListCommand.php
- src/Console/Command/TaskGeneratorCommand.php
- src/Event.php
- src/Finder/Finder.php
- src/Finder/FinderInterface.php
- src/Path/Path.php
- src/Task/Collection.php
- tests/Functional/TaskGeneratorTest.php
- tests/Unit/Console/Command/ScheduleRunCommandTest.php
- tests/Unit/EventTest.php
- tests/Unit/Finder/FinderTest.php
- tests/Unit/Path/PathTest.php
This PR removes symfony\finder dependency and introduces \Crunz\Path\Path class to ease creating file system paths delimited by OS directory separator.
> Remove symfony\finder dependency.

- .travis.yml
On Travis test against PHP 7.3 explicitly because nightly is 7.4-dev now.
> Run tests on PHP 7.3

- README.md
- composer.json
- src/Event.php
- src/EventRunner.php
- tests/Unit/PreventOverlappingTest.php
This PR adds the ability to use a symfony/lock storage to prevent command overlapping, as discussed in #125.
I did not remove the file based locking, as this might be BC break (because of the lockFile() method etc., which is not private). However, this could be removed with the next major release.
This should also solve the request of @IkeLutra, because he can now use the FlockStorage and define the path.
Additionally, I added a unit test that verifies that the task lockig is working properly.
> Add support for symfony/lock

- README.md
Previous badge was confusing because it says "7.1.3", but it was requirement for `v2` not for `v1`.
> Clarify supported PHP versions.

- CHANGELOG.md
- README.md
- crunz
PRs:
- [#168] Add Pull Request template
- [#167] Improve CHANGELOG.md
- [#171] Fix lock storage bug
- [#173] Remove Symfony 4.2 deprecations
- [#170] Use Docker instead of Vagrant in dev
- [#166] Improve task collection debugging
> Release v1.11.0-rc.1

- README.md
- crunz.yml
- src/Configuration/Definition.php
- src/Logger/LoggerFactory.php
- tests/Unit/Logger/FileLoggerTest.php
- tests/crunz.yml
| Fixed ticket | #175 
Crunz timezone in log files is not depending on timezone that is used to calculate task run time.
Because crunz logs my task related event. I set timezone for my tasks, and crunz uses this timezone to run task, thus any logs that related to this task, should be log in configured timezone.
>  fix incorrect timezone in log files

- .travis.yml
- appveyor.yml
- composer.json
- docker/dev-tools/Dockerfile
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
This should speed up CI builds a little bit.
> Move PHPUnit to vendor-bin directory

- README.md
- config/services.php
- docker-compose.yml
- src/Application.php
- src/EnvFlags/EnvFlags.php
- tests/TestCase/EndToEnd/Environment/Environment.php
- tests/Unit/EnvFlags/EnvFlagsTest.php
By default "container debug" was enabled, but there is no need to keep it enabled for end users. This PR disables it for end users and enabled only for development containers, by the way some CPU cycles and disk IO should be saved also on Crunz start up.
> Make "container debug" configurable

- UPGRADE.md
This PR add two missing upgrades, from `v1.7` to `v1.8` and from `v1.9` to `v1.10`.
> Add missing upgrade guides

- composer.json
There is no need to require `symfony/debug` at least on version `3.4.22` for non-dev usages
> Move symfony/debug to dev dependencies

- src/Event.php
- src/Task/TaskException.php
- tests/Unit/EventTest.php
Passing more than five parts to `Crunz\Event::cron()` will now throw exception, as it was deprecated in `v1.9`.
> More than five parts cron expressions will throw exception

- crunz
> #207 - Add Vendor/Bin as source for Autoload discovery

- UPGRADE.md
- phpstan.neon
- src/Exception/MailerException.php
- src/Mailer.php
- tests/Unit/MailerTest.php
SwiftMailer `v6` do not support `mail` transport, so `Crunz` `v2.0` won't support it either.
> Remove 'mail' transport

- src/Filesystem/Filesystem.php
- src/Finder/Finder.php
- src/Finder/FinderInterface.php
- src/Task/Collection.php
- tests/Unit/Finder/FinderTest.php
| Fixed tickets | https://github.com/lavary/crunz/issues/228
This PR will bring back recursive tasks' directory scanning, which was removed by accident.
> Fix recursive tasks scan

- composer.json
| Fixed tickets | #239   
`mtdowling/cron-expression` has been deprecated in favor of `dragonmantank/cron-expression` according to the [README](https://github.com/mtdowling/cron-expression). This PR replaces the deprecated `cron-expression` package for a maintained fork.
Implementation notes
--------------------
Seems to be a drop-in replacement.
> Swap out the cron-expression package

- CHANGELOG.md
- appveyor.yml
For some reason `cinst` is no longer available in AppVeyor CI.
> Fix AppVeyor CI

- CHANGELOG.md
- config/services.php
- src/Console/Command/ScheduleListCommand.php
- src/Console/Command/ScheduleRunCommand.php
- src/Task/Loader.php
- src/Task/LoaderInterface.php
- tests/Unit/Console/Command/ScheduleRunCommandTest.php
| Fixed tickets | #242    
This PR fixes #242 by introducing `\Crunz\Task\LoaderInterface` and `require`ing files in separate, private, method to avoid variables overriding.
> Sandbox task loading

- README.md
| Fixed tickets | #246 
This PR suggests using `PHP_BINARY` const to avoid differences in filesystems'.
> Suggest using PHP_BINARY const

- src/Console/Command/ClosureRunCommand.php
- tests/Unit/Console/Command/ClosureRunCommandTest.php
| Fixed tickets | #260 
Unintended (not documented) BC break was introduced in https://github.com/lavary/crunz/commit/9c9cf9db141594547285f9d5af4ca48d2856891a#diff-99156d24102de67b9de59f1792622c62R36, Closures that were fine in `v1.x` starts to fail in `v2.x`, because they do not return any value.
This PR reverts BC-break change, so behavior will be consistent for `v1.x` and `v2.x`
> Revert converting closure result to int

- CHANGELOG.md
- README.md
- crunz
- [#261] Release lock on error
- [#264] Revert converting closure result to `int`
> Release v2.0.3

- src/Console/Command/ClosureRunCommand.php
- src/Console/Command/TaskGeneratorCommand.php
- src/Process/Process.php
| Fixed tickets | https://github.com/lavary/crunz/issues/267
This PR fixes deprecations from Symfony 4.4, it is also a required step before providing support for Symfony 5.0 (https://github.com/lavary/crunz/issues/265).
> Fix Symfony 4.4 deprecations

- README.md
| Fixed tickets | #...   
Just an update to docs, it wasn't clear why only the BlockingInterface is supported
> Update docs for Symfony 5 locking

- CHANGELOG.md
- README.md
- composer.json
- crunz
- [#287] Add `task:debug` command
- [#288] Improve TravisCI configuration
- [#290] Remove "dev_tools" service from docker-compose
- [#291] Remove box from vendor bin
- [#292] Drop Symfony 4.2 support
- [#294] Update docs for Symfony 5 locking, thanks to @hashnz
- [#233] Add option to ignore empty context in monolog
- [#297] Add ConfigurationInterface
- [#299] Migrate to `opis\closure`
- [#300] Update dev tools
- [#298] Implement logger factory rfc
- [#304] Add "status" column to roadmap
- [#305] Test Symfony 5.1 compatibility
> Release v2.2.0

- CHANGELOG.md
- README.md
- crunz
- [#323] Drop Symfony 4.3 support
- [#324] Drop Symfony 5.0 support
- [#335] Add "code_checks" workflow
- [#336] Fix missing "composer version" command in CI
- [#337] Fix dependencies versions in "static_analysis" job
- [#338] Do not test PHP v8.1
- [#344] Deprecate most "Event::every*" methods
- [#347] Update dev dependencies
> Release v2.3.0

- src/Application/Service/ConfigurationInterface.php
- src/Configuration/Configuration.php
- src/EventRunner.php
- src/Logger/LoggerFactory.php
- tests/EndToEnd/LoggerTest.php
- tests/TestCase/FakeConfiguration.php
- tests/TestCase/PolyfillAssertTrait.php
- tests/Unit/Configuration/ConfigurationTest.php
- tests/Unit/EventRunnerTest.php
- tests/Unit/Logger/LoggerFactoryTest.php
- tests/resources/tasks/CustomOutputTasks.php
> Log to specific event log file

- src/Event.php
- tests/Unit/EventTest.php
| Fixed tickets | #368
Re-implementation of #391
> Add hourly at
